
const EXT2MIME= {
	'atom':    'application/atom+xml',
	'ear':     'application/java-archive',
	'jar':     'application/java-archive',
	'war':     'application/java-archive',
	'js':      'application/javascript',
	'json':    'application/json',
	'hqx':     'application/mac-binhex40',
	'doc':     'application/msword',
	'bin':     'application/octet-stream',
	'deb':     'application/octet-stream',
	'dll':     'application/octet-stream',
	'dmg':     'application/octet-stream',
	'exe':     'application/octet-stream',
	'img':     'application/octet-stream',
	'iso':     'application/octet-stream',
	'msi':     'application/octet-stream',
	'msm':     'application/octet-stream',
	'msp':     'application/octet-stream',
	'pdf':     'application/pdf',
	'ai':      'application/postscript',
	'eps':     'application/postscript',
	'ps':      'application/postscript',
	'rss':     'application/rss+xml',
	'rtf':     'application/rtf',
	'm3u8':    'application/vnd.apple.mpegurl',
	'kml':     'application/vnd.google-earth.kml+xml',
	'kmz':     'application/vnd.google-earth.kmz',
	'xls':     'application/vnd.ms-excel',
	'eot':     'application/vnd.ms-fontobject',
	'ppt':     'application/vnd.ms-powerpoint',
	'odg':     'application/vnd.oasis.opendocument.graphics',
	'odp':     'application/vnd.oasis.opendocument.presentation',
	'ods':     'application/vnd.oasis.opendocument.spreadsheet',
	'odt':     'application/vnd.oasis.opendocument.text',
	'pptx':    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'xlsx':    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'docx':    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'wmlc':    'application/vnd.wap.wmlc',
	'7z':      'application/x-7z-compressed',
	'cco':     'application/x-cocoa',
	'jardiff': 'application/x-java-archive-diff',
	'jnlp':    'application/x-java-jnlp-file',
	'run':     'application/x-makeself',
	'pl':      'application/x-perl',
	'pm':      'application/x-perl',
	'pdb':     'application/x-pilot',
	'prc':     'application/x-pilot',
	'rar':     'application/x-rar-compressed',
	'rpm':     'application/x-redhat-package-manager',
	'sea':     'application/x-sea',
	'swf':     'application/x-shockwave-flash',
	'sit':     'application/x-stuffit',
	'tcl':     'application/x-tcl',
	'tk':      'application/x-tcl',
	'crt':     'application/x-x509-ca-cert',
	'der':     'application/x-x509-ca-cert',
	'pem':     'application/x-x509-ca-cert',
	'xpi':     'application/x-xpinstall',
	'xhtml':   'application/xhtml+xml',
	'xspf':    'application/xspf+xml',
	'zip':     'application/zip',
	'kar':     'audio/midi',
	'mid':     'audio/midi',
	'midi':    'audio/midi',
	'mp3':     'audio/mpeg',
	'ogg':     'audio/ogg',
	'm4a':     'audio/x-m4a',
	'ra':      'audio/x-realaudio',
	'woff':    'font/woff',
	'woff2':   'font/woff2',
	'gif':     'image/gif',
	'jpeg':    'image/jpeg',
	'jpg':     'image/jpeg',
	'png':     'image/png',
	'svg':     'image/svg+xml',
	'svgz':    'image/svg+xml',
	'tif':     'image/tiff',
	'tiff':    'image/tiff',
	'wbmp':    'image/vnd.wap.wbmp',
	'webp':    'image/webp',
	'ico':     'image/x-icon',
	'jng':     'image/x-jng',
	'bmp':     'image/x-ms-bmp',
	'css':     'text/css',
	'htm':     'text/html',
	'html':    'text/html',
	'shtml':   'text/html',
	'mml':     'text/mathml',
	'txt':     'text/plain',
	'jad':     'text/vnd.sun.j2me.app-descriptor',
	'wml':     'text/vnd.wap.wml',
	'htc':     'text/x-component',
	'xml':     'text/xml',
	'3gp':     'video/3gpp',
	'3gpp':    'video/3gpp',
	'ts':      'video/mp2t',
	'mp4':     'video/mp4',
	'mpeg':    'video/mpeg',
	'mpg':     'video/mpeg',
	'mov':     'video/quicktime',
	'webm':    'video/webm',
	'flv':     'video/x-flv',
	'm4v':     'video/x-m4v',
	'mng':     'video/x-mng',
	'asf':     'video/x-ms-asf',
	'asx':     'video/x-ms-asf',
	'wmv':     'video/x-ms-wmv',
	'avi':     'video/x-msvideo',
};

const MIME2EXT= {
	'application/atom+xml':                                                        'atom',
	'application/java-archive':                                                    'jar',
	'application/javascript':                                                      'js',
	'application/json':                                                            'json',
	'application/mac-binhex40':                                                    'hqx',
	'application/msword':                                                          'doc',
	'application/octet-stream':                                                    'bin',
	'application/pdf':                                                             'pdf',
	'application/postscript':                                                      'ps',
	'application/rss+xml':                                                         'rss',
	'application/rtf':                                                             'rtf',
	'application/vnd.apple.mpegurl':                                               'm3u8',
	'application/vnd.google-earth.kml+xml':                                        'kml',
	'application/vnd.google-earth.kmz':                                            'kmz',
	'application/vnd.ms-excel':                                                    'xls',
	'application/vnd.ms-fontobject':                                               'eot',
	'application/vnd.ms-powerpoint':                                               'ppt',
	'application/vnd.oasis.opendocument.graphics':                                 'odg',
	'application/vnd.oasis.opendocument.presentation':                             'odp',
	'application/vnd.oasis.opendocument.spreadsheet':                              'ods',
	'application/vnd.oasis.opendocument.text':                                     'odt',
	'application/vnd.openxmlformats-officedocument.presentationml.presentation':   'pptx',
	'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':           'xlsx',
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document':     'docx',
	'application/vnd.wap.wmlc':                                                    'wmlc',
	'application/x-7z-compressed':                                                 '7z',
	'application/x-cocoa':                                                         'cco',
	'application/x-java-archive-diff':                                             'jardiff',
	'application/x-java-jnlp-file':                                                'jnlp',
	'application/x-makeself':                                                      'run',
	'application/x-perl':                                                          'pl',
	'application/x-pilot':                                                         'prc',
	'application/x-rar-compressed':                                                'rar',
	'application/x-redhat-package-manager':                                        'rpm',
	'application/x-sea':                                                           'sea',
	'application/x-shockwave-flash':                                               'swf',
	'application/x-stuffit':                                                       'sit',
	'application/x-tcl':                                                           'tcl',
	'application/x-x509-ca-cert':                                                  'der',
	'application/x-xpinstall':                                                     'xpi',
	'application/xhtml+xml':                                                       'xhtml',
	'application/xspf+xml':                                                        'xspf',
	'application/zip':                                                             'zip',
	'audio/midi':                                                                  'mid',
	'audio/mpeg':                                                                  'mp3',
	'audio/ogg':                                                                   'ogg',
	'audio/x-m4a':                                                                 'm4a',
	'audio/x-realaudio':                                                           'ra',
	'font/woff':                                                                   'woff',
	'font/woff2':                                                                  'woff2',
	'image/gif':                                                                   'gif',
	'image/jpeg':                                                                  'jpg',
	'image/png':                                                                   'png',
	'image/svg+xml':                                                               'svg',
	'image/tiff':                                                                  'tif',
	'image/vnd.wap.wbmp':                                                          'wbmp',
	'image/webp':                                                                  'webp',
	'image/x-icon':                                                                'ico',
	'image/x-jng':                                                                 'jng',
	'image/x-ms-bmp':                                                              'bmp',
	'text/css':                                                                    'css',
	'text/html':                                                                   'html',
	'text/mathml':                                                                 'mml',
	'text/plain':                                                                  'txt',
	'text/vnd.sun.j2me.app-descriptor':                                            'jad',
	'text/vnd.wap.wml':                                                            'wml',
	'text/x-component':                                                            'htc',
	'text/xml':                                                                    'xml',
	'video/3gpp':                                                                  '3gp',
	'video/mp2t':                                                                  'ts',
	'video/mp4':                                                                   'mp4',
	'video/mpeg':                                                                  'mpg',
	'video/quicktime':                                                             'mov',
	'video/webm':                                                                  'webm',
	'video/x-flv':                                                                 'flv',
	'video/x-m4v':                                                                 'm4v',
	'video/x-mng':                                                                 'mng',
	'video/x-ms-asf':                                                              'asx',
	'video/x-ms-wmv':                                                              'wmv',
	'video/x-msvideo':                                                             'avi',
};

/**
 * Extension name to MIME type
 * 
 * @param ext (string)  extension name
 * 
 * @return (string)     MIME type
 */
export function ext2mime( ext, )
{
	ext= ext.replace( /[^.]*\./g, '', );
	
	return EXT2MIME[ext] || 'application/octet-stream';
}

/**
 * MIME type to Extension name
 * 
 * @param mime (string)   MIME type
 * 
 * @return ext (string)   extension name
 */
export function mime2ext( mime, )
{
	return MIME2EXT[mime] || null;
}
